### ISSUE TITLE
limitations of text rendering in canvas

### ISSUE THREAD

**Issue by mikefills** [danielearwicker/carota#36]
First, you've done some nice work in Carota!
You have a lot of experience with canvas, can I ask you what kind of limitations do you see with rendering text in canvas?
For example, would it possible to use any kind of font? In the Carota demo there are only a few. 
What is the support for text metrics?

Thanks!

**Comment by danielearwicker** [comment]
Thanks, I wish I had more time to work on it! Seems other people are using it though (or at least playing with it and learning) so that's great.

I don't know of any limitations on fonts in canvas relative to other browser capabilities. In some browsers/platforms there have been reports of it being slow or fuzzy looking but those are the kinds of things that get fixed.

However canvas support for text metrics in canvas's standard API is (or was) very weak. I summarized how to get the basic dimensions needed for text wrapping in this answer, and this is essentially what happens inside Carota:

http://stackoverflow.com/a/9847841

See `carota/text.js` which contains the `measureText` function.
